export const metadata = {
    title: "Blogs list",
    description: "Generated by Hung Truong",
};

export default function BlogsLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <>{children}</>;
}
