export const metadata = {
    title: "Blog detail",
    description: "Generated by Hung Truong",
};

export default function DetailLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <>{children}</>;
}
